hospital/hospital/urls.py
from django.contrib import admin

from django.urls import path
from django.urls import include

from django.conf.urls.static import static
from django.conf import settings

from . import views

from resources.views import ResourceListView

urlpatterns = [
    path('',ResourceListView.as_view(),name='index'),
    path('usuarios/login',views.login_view,name='login'),
    path('usuarios/logout',views.logout_view,name='logout'),
    path('usuarios/registro',views.register,name='register'),
    path('admin/', admin.site.urls),
    path('recursos/',include('resources.urls')),
    path('recursosPedidos/',include('resourcesAllocation.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

hospital/resourcesAllocation/urls.py
from django.urls import path

from . import views
app_name = 'resourcesAllocation'

urlpatterns = [
    path('',views.resourceAllocation,name = 'resourceAllocation'),
    path('agregar',views.add, name = 'add'),
    path('eliminar',views.remove, name = 'remove')
]

hospital/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  </head>
  <body>

    {% include 'navbar.html'%}

    <div class="container">

      {% include 'messages.html' %}

      <div class="row mt-5">
        {% block content %}
        {% endblock  %}
      </div>
    </div>
  </body>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  <script src="https://kit.fontawesome.com/adb58a94c8.js" crossorigin="anonymous"></script>
</html>

hospital/templates/index.html
{% extends 'base.html' %}

{% block content %}


<div class="col">
    <h4 class="text-center">{{message}}</h4>
      {% include 'resources/snippets/search.html' %}

      {% include 'resources/snippets/list.html'%}

  </div>
{% endblock %}

hospital/templates/messages.html
{% if messages %}
  {% for message in messages %}
    <div class="alert {% if message.tags == 'success'%}alert-success{%else%}alert-danger{%endif%}">
      <button type="button" class="close" data-dismiss="alert">x</button>
        {{message}}
    </div>
  {% endfor %}
{% endif %}

hospital/templates/navbar.html
{% url 'login' as login %}
{% url 'register' as register %}
{% url 'logout' as logout %}
{% url 'resourcesAllocation:resourceAllocation' as resourceAllocation %}

<nav class="navbar navbar-expand-md bg-dark navbar-dark">
  <a href="{% url 'index' %}" class="navbar-brand">Hospital</a>

  <button type="button" name="button" class="navbar-toggler navbar-toggler-right" data-toggle="collapse" data-target="#navb">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div id="navb" class="navbar-collapse collapse hide">

    <ul class="navbar-nav">
        <li class="nav-item {% if request.path == resourceAllocation %}active {%endif%}">
          <a class="nav-link" href="{{resourceAllocation}}">
            Mis pedidos <span class="fa fa-microchip"></span>
          </a>
        </li>
    </ul>

    <ul class="nav navbar-nav ml-auto">

      {% if user.is_authenticated %}
        <li class="navbar-item">
          <a href="{{logout}}" class="nav-link">
            <span class="fas fa-sign-in-alt"></span>
             Logout </a>
        </li>
      {% else %}
        <li class="navbar-item {% if request.path == login %}active{% endif %}">
          <a href="{{login}}" class="nav-link">
            <span class="fas fa-user"></span>
            Login</a>
        </li>

        <li class="navbar-item {% if request.path == register %}active{% endif %}">
          <a href="{{register}}" class="nav-link">
            <span class="fas fa-user-plus"></span>
            Registo</a>
        </li>
      {% endif %}

    </ul>
  </div>
</nav>