hospital/hospital/urls.py
from django.contrib import admin

from django.urls import path
from django.urls import include

from django.conf.urls.static import static
from django.conf import settings

from . import views

from resources.views import ResourceListView

urlpatterns = [
    path('',ResourceListView.as_view(),name='index'),
    path('usuarios/login',views.login_view,name='login'),
    path('usuarios/logout',views.logout_view,name='logout'),
    path('usuarios/registro',views.register,name='register'),
    path('admin/', admin.site.urls),
    path('recursos/',include('resources.urls')),
    path('recursosPedidos/',include('resourcesAllocation.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

hospital/resourcesAllocation/urls.py
from django.urls import path

from . import views
app_name = 'resourcesAllocation'

urlpatterns = [
    path('',views.resourceAllocation,name = 'resourceAllocation'),
    path('agregar',views.add, name = 'add'),
    path('eliminar',views.remove, name = 'remove')
]

hospital/resourcesAllocation/models.py
import uuid
from django.db import models

from users.models import User
from resources.models import Resource

from django.db.models.signals import pre_save

class ResourceAllocation(models.Model):
    resourceAllocation_id = models.CharField(max_length=100, null=False, blank = False, unique=True )
    user = models.ForeignKey(User,null = True,blank= True, on_delete= models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    type = models.CharField(max_length=50)
    createdStart = models.DateTimeField(null = True)
    createdEnd = models.DateTimeField(null = True)

    #resources = models.ForeignKey(Resource, blank = True, null = True, on_delete = models.SET_NULL)
    resources = models.ManyToManyField(Resource,through='ResourceAllocationResources')

    def __str__(self):
        return self.resourceAllocation_id

    def resources_related(self):
        return self.resourceallocationresources_set.select_related('resources')

class ResourceAllocationResourcesManager(models.Manager):

        def create_or_update_quantity(self,resourceAllocation,resources,quantity=1):
            object, created = self.get_or_create(resourceAllocation=resourceAllocation,resources=resources)

            if not created:
                object.quantity += quantity
                object.save()
            return object
class ResourceAllocationResources(models.Model):
    resourceAllocation = models.ForeignKey(ResourceAllocation,on_delete=models.CASCADE)
    resources = models.ForeignKey(Resource,on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True )

    objects = ResourceAllocationResourcesManager()

def set_resourceAllocation_id(sender,instance,*args,**kwargs):
    if not instance.resourceAllocation_id:
        instance.resourceAllocation_id = str(uuid.uuid4())

pre_save.connect(set_resourceAllocation_id,sender=ResourceAllocation)

hospital/resourcesAllocation/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404

from.models import ResourceAllocationResources
from resources.models import Resource

from .models import ResourceAllocation
from .utils import get_or_create_resourceAllocation

def resourceAllocation(request):
    #request.session['resourceAllocation_id'] = None
    resourceAllocation = get_or_create_resourceAllocation(request)

    return render(request,'resourcesAllocation/resourceAllocation.html',{
        'resourceAllocation':resourceAllocation
    })

def add(request):
    resourceAllocation = get_or_create_resourceAllocation(request)
    resources = get_object_or_404(Resource,pk=request.POST.get('resource_id'))
    quantity = request.POST.get('quantity',1)

    #resourceAllocation.resources.add(resource, through_defaults={
    #    'quantity': quantity
    #})

    resourceallocation_resources = ResourceAllocationResources.objects.create(resourceAllocation=resourceAllocation,
                                                resources=resources,quantity=quantity)
    return render(request, 'resourcesAllocation/add.html',{
        'resource':resources
    })

def remove(request):
    resourceAllocation = get_or_create_resourceAllocation(request)
    resource = get_object_or_404(Resource, pk=request.POST.get('resource_id'))

    resourceAllocation.resources.remove(resource)

    return redirect('resourcesAllocation:resourceAllocation')

hospital/resourcesAllocation/templates/resourcesAllocation/snippets/add.html
<form action="{% url 'resourcesAllocation:add' %}" method="post">
  {% csrf_token %}
  <input type="hidden" name="resource_id" value="{{resource.id}}">
  <div class="">
      <button type="button" class="btn btn-info d-inline" id="remove">-</button>
      <input type="number" value="1" class="form-control col-sm-1 d-inline" id="quantity" name="quantity" readonly>
      <button type="button" class="btn btn-info" id="add">+</button>
  </div>

  <div class="mt-2">
      <button type="submit" class="btn btn-warning">Agregar a pedidos</button>
  </div>
</form>

<script>

  const add = document.getElementById('add')
  const remove = document.getElementById('remove')
  const quantity = document.getElementById('quantity')

  add.addEventListener('click', function(){
    quantity.value = parseInt(quantity.value) + 1
  })
  remove.addEventListener('click', function(){
    value = parseInt(quantity.value)
    if (value != 1){
      value = value - 1
    }
    quantity.value = value
  })

</script>

hospital/resourcesAllocation/templates/resourcesAllocation/snippets/remove.html
<form action="{% url 'resourcesAllocation:remove' %}" method="post">
  {% csrf_token %}
  <input type="hidden" name="resource_id" value="{{resource.id}}">
  <button type="submit" class="btn btn-link text-danger" style="padding:0px">Eliminar</button>
</form>