hospital/hospital/urls.py
from django.contrib import admin

from django.urls import path
from django.urls import include

from django.conf.urls.static import static
from django.conf import settings

from . import views

from resources.views import ResourceListView

urlpatterns = [
    path('',ResourceListView.as_view(),name='index'),
    path('usuarios/login',views.login_view,name='login'),
    path('usuarios/logout',views.logout_view,name='logout'),
    path('usuarios/registro',views.register,name='register'),
    path('admin/', admin.site.urls),
    path('recursos/',include('resources.urls')),
    path('recursosPedidos/',include('resourcesAllocation.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

hospital/resources/urls.py
from django.urls import path

from . import views

app_name = 'resources'

urlpatterns = [
    path('search',views.ResourceSearchListView.as_view(), name='search'),
    path('<slug:slug>', views.ResourceDetailView.as_view(),name='resource'),
]

hospital/resources/templates/resources/snippets/list.html
<div class="row">
  {% for object in object_list %}
    <div class="col-3 mt-5">
      {% include 'resources/snippets/resource.html' with resource=object %}
    </div>
  {% endfor %}
</div>

hospital/resources/templates/resources/snippets/resource.html
<!-- Resource -->
<div class="card h-100">

  {% if resource.image %}
    <img src="{{resource.image.url}}" alt="Imagen del recurso" height="250">
  {% endif %}

  <div class="card-body">
    <h5 class="card.title">{{resource.type}}</h5>
    <p class="card-text">{{resource.description}}</p>
    <a href="{% url 'resources:resource' resource.slug %}" class="btn btn-primary">Ver mas</a>
  </div>
</div>

hospital/resources/templates/resources/snippets/search.html
<form action="{% url 'resources:search' %}" >
  <div class="input-group">
    <input type="text" name="q" value="{{ query }}" class="form-control" placeholder="Buscar">
    <div class="input-group-append">
      <input type="submit" name="" value="Buscar" class="btn btn-primary">
    </div>
  </div>
</form>